- name: start redis and only run when pidfile doesn't exits
  shell:
    cmd: "netstat -nltp|grep {{ nutcracker_port }}|awk '{print $4}'|rev|cut -d':' -f1|rev" 
  register: out

- name: deploy if {{ nutcracker_port }} not exits
  import_tasks: nutcracker.yml
  when: out.rc == 0 and out.stdout  == ""
