
- name: create depoly dir if not exits
  file:
    path: "{{ item }}"
    mode: 0755
    force: no
    state: directory
  with_items:
      - "{{ deploy_dir }}"

- name: cp package and unarchive to remote machine if not exits
  unarchive:
    src: output.tgz
    dest: "{{ deploy_dir }}"
    remote_src: no
    creates: "{{ base_dir }}"

- name: "check if {{ package_dir }} exits "
  stat:
    path: "{{ package_dir }}"
  register: src_stat

- name: "check if {{ base_dir }} exits"
  stat:
    path: "{{ base_dir }}"
  register: dest_stat

- name: copy {{ package_dir }} to base_dir
  command: "cp -r {{ package_dir }} {{ base_dir }}"
  when: src_stat.stat.exists and not dest_stat.stat.exists

- name: create deploy directories if not exits
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    force: no
  with_items:
    - "{{ conf_dir }}"
    - "{{ logfile_dir }}"
    - "{{ script_dir }}"
    - "{{ whitelist_file_dir }}"
    - "{{ pidfile_dir }}"

- name: generate whitelist bns if not exits
  template:
    src: whitelist_bns.j2
    dest: "{{ whitelist_file_bns }}"
    mode: 0644
    force: no

- name: generate whitelist ip if not exits
  template:
    src: whitelist_ip.j2
    dest: "{{ whitelist_file_ip }}"
    mode: 0644
    force: no

- name: generate config if not exits
  template:
    src: nutcracker.conf.j2
    dest: "{{ conf_file }}"
    mode: 0644
    force: yes

- name: generate service control scripts if not exits
  template:
    src: nutcracker_service.sh
    dest: "{{ nutcracker_control_script }}"
    mode: 0775
    force: yes

- name: start nutcracker if {{ nutcracker_port }} stop
  shell:
    cmd: "{{ nutcracker_control_script }} start {{ nutcracker_port }}"
  register: start_out

- name: check nutcracker status
  debug: msg={{ start_out.stdout }}

- name: clear
  file:
    path: "{{ package_dir }}"
    state: absent
